get http://localhost:8000/

###

post http://localhost:8000/backoffice
Content-Type: application/json

{
    "title":"Le doublé",
    "description":"Gagner le top14 en surveillance et analysant les équipes adversaires",
    "codename":"velodrome",
    "status":"En préparation",
    "type":"surveillance",
    "id_agent":"64776736-1d03-11ef-bb78-58a023d3f752",
    "id_contact":"7e9edcd6-1d03-11ef-bb78-58a023d3f752",
    "id_hideout":"7e9bdf2f-1d03-11ef-bb78-58a023d3f752",
    "id_speciality":"ca9acb8f-1d02-11ef-bb78-58a023d3f752",
    "id_target":"7e99594d-1d03-11ef-bb78-58a023d3f752",
    "id_origin":"ca9d43fa-1d02-11ef-bb78-58a023d3f752",
    "start_date":"2023-05-26",
    "end_date":"2023-06-28"
}

###

put http://localhost:8000/backoffice/f78251d0-1e9d-11ef-87ab-58a023d3f752
Content-Type: application/json

{
    "title":"Le doublé pour 2024",
    "description":"Gagner le top14 en surveillant et analysant le jeu des équipes adversaires",
    "codename":"velodrome",
    "status":"En préparation",
    "type":"surveillance",
    "id_agent":"64776736-1d03-11ef-bb78-58a023d3f752",
    "id_contact":"7e9edcd6-1d03-11ef-bb78-58a023d3f752",
    "id_hideout":"7e9bdf2f-1d03-11ef-bb78-58a023d3f752",
    "id_speciality":"ca9acb8f-1d02-11ef-bb78-58a023d3f752",
    "id_target":"7e99594d-1d03-11ef-bb78-58a023d3f752",
    "id_origin":"ca9d43fa-1d02-11ef-bb78-58a023d3f752",
    "start_date":"2023-05-26",
    "end_date":"2023-06-28"
}

###

delete  http://localhost:8000/backoffice/f78251d0-1e9d-11ef-87ab-58a023d3f752

###

post http://localhost:8000/users
Content-Type: application/json

{
    "firstname":"Thomas",
    "lastname":"Ramos",
    "mail":"thomasramos@test.com",
    "isAdmin": false,
    "password":"Mathys31!" 
}


###

put http://localhost:8000/users/6659d462dda961bc37af4b48
Content-Type: application/json

{
    "firstname":"Thomas",
    "lastname":"Ramos",
    "mail":"",
    "isAdmin": true,
    "password":"Totom31!" 
}

###

get http://localhost:8000/users

###
post http://localhost:8000/login
Content-Type: application/json

 {
    "mail":"mathyslebel@test.com",
    "password":"Mathys31!"
 }


###

delete http://localhost:8000/users/6659d462dda961bc37af4b48

###

get http://localhost:8000/backoffice