get http://localhost:8000/

###

post http://localhost:8000/backoffice
Content-Type: application/json

{
    "title":"vol de la coupe d'Europe",
    "description":"La coupe gagnée samedi a été volé par le capitaine irlandais",
    "codename":"et à la fin c'est Toulouse qui gagne",
    "status":"Terminée",
    "type":"assassinat",
    "id_agent":"786c002f-3ad8-11ef-b84e-58a023d3f752",
    "id_contact":"7876f404-3ad8-11ef-b84e-58a023d3f752",
    "id_hideout":"7872b13d-3ad8-11ef-b84e-58a023d3f752",
    "id_speciality":"78661c65-3ad8-11ef-b84e-58a023d3f752",
    "id_target":"786f2400-3ad8-11ef-b84e-58a023d3f752",
    "id_origin":"7869110d-3ad8-11ef-b84e-58a023d3f752",
    "start_date":"2023-05-26",
    "end_date":"2023-06-28"
}

###

put http://localhost:8000/backoffice/6541694b-644e-11ef-b0ae-58a023d3f752
Content-Type: application/json


{
    "title":"vol de la coupe d'Europe 2024",
    "description":"La coupe gagnée samedi a été volé par le capitaine irlandais",
    "codename":"et à la fin c'est Toulouse qui gagne !",
    "status":"Terminée",
    "type":"assassinat",
    "id_agent":"786c002f-3ad8-11ef-b84e-58a023d3f752",
    "id_contact":"7876f404-3ad8-11ef-b84e-58a023d3f752",
    "id_hideout":"7872b13d-3ad8-11ef-b84e-58a023d3f752",
    "id_speciality":"78661c65-3ad8-11ef-b84e-58a023d3f752",
    "id_target":"786f2400-3ad8-11ef-b84e-58a023d3f752",
    "id_origin":"7869110d-3ad8-11ef-b84e-58a023d3f752",
    "start_date":"2023-05-26",
    "end_date":"2023-06-28"
}

###

delete  http://localhost:8000/backoffice/f78251d0-1e9d-11ef-87ab-58a023d3f752

###

post http://localhost:8000/users
Content-Type: application/json

{
    "firstname":"Thomas",
    "lastname":"Ramos",
    "mail":"thomasramos@test.com",
    "isAdmin": false,
    "password":"Mathys31!" 
}


###

put http://localhost:8000/users/66685f9c397eb7c3116abf88
Content-Type: application/json

{
    "firstname":"Thomas",
    "lastname":"Ramos",
    "mail":"thomasramos@test.com",
    "isAdmin": true,
    "password":"Mathys31!" 
}

###

get http://localhost:8000/users

###
post http://localhost:8000/signin
Content-Type: application/json

 {
    "mail":"thomasramos@test.com",
    "password":"Mathys31!"
 }


###

delete http://localhost:8000/users/6659d462dda961bc37af4b48

###

get http://localhost:8000/backoffice